<?php
/**
 * @file
 * prometheus_views.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function prometheus_views_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'views_defaults';
  $strongarm->value = array(
    'taxonomy_term' => TRUE,
    'semantic_demo' => TRUE,
    'front_feature' => TRUE,
    'revisioning_content_revisions_summary' => TRUE,
    'revisioning_content_summary' => TRUE,
    'comments_block' => TRUE,
  );
  $export['views_defaults'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'views_field_rewrite_elements';
  $strongarm->value = array(
    '' => '- Use default -',
    0 => '- None -',
    'div' => 'DIV',
    'span' => 'SPAN',
    'h1' => 'H1',
    'h2' => 'H2',
    'h3' => 'H3',
    'h4' => 'H4',
    'h5' => 'H5',
    'h6' => 'H6',
    'p' => 'P',
    'strong' => 'STRONG',
    'em' => 'EM',
    'article' => 'Article',
    'aside' => 'Aside',
    'footer' => 'Footer',
    'header' => 'Header',
    'menu' => 'Menu',
    'nav' => 'Nav',
  );
  $export['views_field_rewrite_elements'] = $strongarm;

  return $export;
}
